spring:
  datasource:
    url: jdbc:mysql://mysql:3306/resilient_tasks_db
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
jwt:
  secret: ${JWT_SECRET:resilienttasksSuperSecureJwtKey123456}
  expiration-ms: ${JWT_EXPIRATION_MS:86400000}

